# Generated by Django 3.1.4 on 2021-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_auto_20210312_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='displaypic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1500)),
            ],
        ),
    ]
